import { getCookie } from "cookies-next";
import { GetServerSideProps } from "next";
import Head from "next/head";
import Link from "next/link";
import * as React from "react";
import { ButtonDefault } from "../components/button";
import { Input } from "../components/input";
import { FORGOT_PASSWORD_FORM } from "../constant/input";

export interface FortgotPasswordProps {}

export default function ForgotPasswordPage(props: FortgotPasswordProps) {
  return (
    <div className="flex flex-col min-h-screen overflow-hidden">
      <Head>
        <title>Forgot Password</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex-grow z-0">
        <section className="relative">
          <div className="max-w-6xl mx-auto px-5 sm:px-6">
            <div className="pt-32 pb-12 md:pt-40 md:pb-20">
              <div className="max-w-3xl mx-auto text-center pb-12 md:pb-20">
                <h1 className="font-extrabold title-sign">
                  Let’s get you back up on your feet
                </h1>
                <p className="mt-4 text-sign">
                  Enter the email address you used when you signed up for your
                  account, and we’ll email you a link to reset your password.
                </p>
              </div>
              <form className="max-w-sm mx-auto flex-col flex">
                {FORGOT_PASSWORD_FORM.map((input: any, index: number) => {
                  return <Input input={input} key={index} />;
                })}
                <ButtonDefault title={"Reset Password"} />
                <div className="text-center">
                  <Link href="sign-up">
                    <a className="/sign-in">Cancel</a>
                  </Link>
                </div>
              </form>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
