import * as React from "react";
import Head from "next/head";
import Link from "next/link";
import { ButtonAuthGoogle, ButtonDefault } from "../components/button";
import { Input } from "../components/input";
import { SIGNUP_FORM } from "../constant/input";
import { UserAPI } from "../api/index";
import Router from "next/router";
export interface SignUpProps {}

export default function SignUpPage(props: SignUpProps) {
  const signUp = async (e: any) => {
    e.preventDefault();
    const responseSignUp = await UserAPI.signUp(
      e.target.email.value,
      e.target.password.value,
      e.target.yourName.value
    );
    if (responseSignUp?.data.status === "Success") {
      Router.push("/dashboard");
    } else {
      window.alert("sign up fail");
    }
  };
  return (
    <div className="flex flex-col min-h-screen overflow-hidden">
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex-grow z-0">
        <section className="relative">
          <div className="max-w-6xl mx-auto px-5 sm:px-6">
            <div className="pt-32 pb-12 md:pt-40 md:pb-20">
              <div className="max-w-3xl mx-auto text-center pb-12 md:pb-20">
                <h1 className="font-extrabold title-sign">
                  Easily create, customize and embed a video
                </h1>
                <p className="mt-4 text-sign">
                  You will get 1 embed video for free. Try it out 👇
                </p>
              </div>
              <ButtonAuthGoogle title="sign up with Google" />
              <div className="max-w-sm items-center mx-auto flex justify-center my-6">
                <div className="flex items-center border-t border-gray-500 dark:border-gray-700 border-dotted flex-grow mr-3"></div>
                <p className="sign-text">Or, sign in with your email</p>
                <div className="flex items-center border-t border-gray-500 dark:border-gray-700 border-dotted flex-grow ml-3"></div>
              </div>
              <form
                className="max-w-sm mx-auto flex-col flex"
                onSubmit={signUp}
              >
                {SIGNUP_FORM.map((input: any, index: number) => {
                  return <Input input={input} key={index} />;
                })}
                <ButtonDefault title={"Sign up"} />
                <div className="text-center">
                  {`Already have an account?`}
                  <Link href="/sign-in">
                    <a className="sign-a"> Sign in</a>
                  </Link>
                </div>
              </form>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
